#!/usr/bin/env bash

source script-helpers.sh
source trap.sh
source init.sh

set -x
output_filename="${1:-${file_prefix}.list}"
aws s3api list-objects-v2 \
  --bucket "${bucket_name}" \
  --query "Contents[?StorageClass=='GLACIER']" \
  --output json \
  | jq -r '.[].Key' \
    >"${output_filename}"

if [[ "$(wc -l <"${output_filename}")" == '0' ]]; then
  exit 1
fi
