#!/usr/bin/env bash
set -uo pipefail

source script-helpers.sh
source trap.sh
source init.sh

./disable-lifecycle
./list
./copy "${file_prefix}.list"
./list
./restore "${file_prefix}.list"
./check_files "${file_prefix}.list"
./copy "${file_prefix}.restored"
./list
